# Generated by Django 3.0.7 on 2020-06-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Butaca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fila', models.CharField(max_length=2)),
                ('num_butaca', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField()),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('tarifa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sala', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('butacas', models.ManyToManyField(to='pelicula.Butaca')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Cliente')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Funcion')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('duracion', models.IntegerField()),
                ('sinopsis', models.TextField()),
                ('reparto', models.CharField(blank=True, max_length=500, null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='pictures/pelicula')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='funcion',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Pelicula'),
        ),
        migrations.AddField(
            model_name='funcion',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Sala'),
        ),
        migrations.AddField(
            model_name='butaca',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Sala'),
        ),
    ]
